# Development Override Configuration
# Copy this file to docker-compose.override.yml to enable development features and testing

version: '3.8'

services:
  # Enable Traefik dashboard in development
  traefik:
    ports:
      - "8080:8080"  # Dashboard port
    
  # Add development tools
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   restart: unless-stopped
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_PORT=3306
  #   networks:
  #     - traefik-public
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN}`)"
  #     - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
  #     - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
  #     - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  # Add monitoring stack
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: unless-stopped
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - traefik-public
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
  #     - "traefik.http.routers.prometheus.entrypoints=websecure"
  #     - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
  #     - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   restart: unless-stopped
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - ./monitoring/grafana:/var/lib/grafana
  #   networks:
  #     - traefik-public
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
  #     - "traefik.http.routers.grafana.entrypoints=websecure"
  #     - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
  #     - "traefik.http.services.grafana.loadbalancer.server.port=3000" 
