# Traefik v2.10 - Enterprise Reverse Proxy Configuration
# Author: Senior DevOps Engineer
# Version: 1.0.0

# API and Dashboard Configuration
api:
  dashboard: true
  insecure: false
  debug: false

# Entry Points Configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
          priority: 1
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "${DOMAIN}"
            sans:
              - "*.${DOMAIN}"

# Service Discovery Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public
    watch: true
    swarmMode: false
  file:
    directory: /etc/traefik
    watch: true

# Certificate Management
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
      storage: /acme.json
      httpChallenge:
        entryPoint: web
      caServer: https://acme-v02.api.letsencrypt.org/directory

# Logging Configuration
log:
  level: INFO
  format: json

# Access Logging
accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep 